немного переделанное задание к части4
slim1979/tn pull request #6
Opened 2017-05-23 02:00 UTC by slim1979

2017-05-23 06:23 UTC, palkan-th requested changes
- Учимся писать аккуратный код
- Смотрим мастер-класс http://connect.thinknetica.com/t/19-03-2015-20-00-msk-master-klass-pochemu-kod-dolzhen-byt-stilnym/891/21
- Настраиваем Rubocop

2017-05-23 06:23 UTC, palkan-th commented on app/controllers/answers_controller.rb
> +    if params[:id]
И что это у нас тут происходит? Внимательно пересмотри видео, почитай про CRUD.

Не надо превращать Ruby в PHP и всю логику впихивать в одно действие.

2017-05-23 06:23 UTC, palkan-th commented on config/application.rb
> +		config.generators do |g|
Знаешь как отличить скопированный откуда-то код, от написанного самим? Например, по кривому форматированию.

Приведи код в порядок: табов быть не должно, код должен быть аккуратный. Выполняет код машина, которой всё равно, а вот читают люди.

2017-05-23 06:23 UTC, palkan-th commented on config/routes.rb
> +	resources :questions
И тут бардак.

2017-05-23 06:23 UTC, palkan-th commented on spec/controllers/answers_controller_spec.rb
> +  let(:answer) { question.answers.create(body: '123') }
Используй фабрики для создания. Так не придётся добавлять новые обязательные параметры, когда они появятся, обо всём позаботится фабрика.

2017-05-23 06:23 UTC, palkan-th commented on spec/factories/answers.rb
>      body "MyText"
У ответа еще есть вопрос. Фабрика должна быть _валидной_ по умолчанию (т.е. вызов `create(:answer)` должен создавать ответ, а не падать с ошибкой).

2017-05-23 06:23 UTC, palkan-th commented on spec/factories/questions.rb
> +		title nil
Поправить форматирование.

2017-05-23 06:23 UTC, palkan-th commented on spec/spec_helper.rb
> +	config.include FactoryGirl::Syntax::Methods
Поправить форматирование.

2017-05-23 20:40 UTC, slim1979 commented on config/application.rb
> +		config.generators do |g|
насчет скопированного откуда то кода не понял... это код из скринкаста. настройка генератора рельсов. что не так?

2017-05-23 20:40 UTC, slim1979 commented on app/controllers/answers_controller.rb
> +    if params[:id]
можно чуть подробнее?  в чем проблема в этом участке кода?

2017-05-23 20:41 UTC, slim1979 commented on config/routes.rb
> +	resources :questions
не знаю, почему тут так отображается, у меня атом настроен на 2 пробела. специально заглянул - там ровно 2

2017-05-23 20:43 UTC, slim1979 commented on spec/controllers/answers_controller_spec.rb
> +  let(:answer) { question.answers.create(body: '123') }
подскажи, как должна выглядеть фабрика в это случае? 
просто прописать вот так?
```
  factory :answer_to_question, class: 'Answer' do
    question.answers.create(body: '123')
  end
```

2017-05-23 20:45 UTC, slim1979 commented on spec/factories/answers.rb
>      body "MyText"
ну это видимо к моему вопросу выше

2017-05-23 20:46 UTC, slim1979 commented on spec/factories/questions.rb
> +		title nil
поправил

2017-05-23 20:47 UTC, slim1979 commented on spec/spec_helper.rb
> +	config.include FactoryGirl::Syntax::Methods
поправил

2017-05-24 17:27 UTC, palkan-th commented on config/routes.rb
> +	resources :questions
Это не пробелы, а табуляция.
Поэтому и отображается по-разносу.

2017-05-24 17:33 UTC, palkan-th commented on spec/controllers/answers_controller_spec.rb
> +  let(:answer) { question.answers.create(body: '123') }
Во-первых, это код работать не будет.
Во-вторых, документация к FactoryGirl подскажет https://github.com/thoughtbot/factory_girl/blob/master/GETTING_STARTED.md. Там все отлично описано.

2017-05-24 17:34 UTC, palkan-th commented on config/application.rb
> +		config.generators do |g|
Форматирование не так

2017-05-25 21:00 UTC, closed without merging